src/command.js

Remove the default cypress screenshot flag as it is up to the user to disable it when needed.

feat: remove disable screenshot flag

---

src/command.js

Starting Cypress 9, it will throw an error if Cypress.config validation is incorrect. Reference - https://github.com/cypress-io/cypress/pull/18589
This is the error we have on our current project:

update height and width values of Cypress config

---

src/command.js

fixes https://github.com/uktrade/cypress-image-diff/issues/50

fix: ensure viewport is read as a number rather than a string

---

src/utils.js
src/utils.test.js

When comparing snapshots the screenshots are left in the configured screenshots folder of cypress even when there is no difference detected. Files in the screenshot folder usually indicates some sort of problem. Moving them makes sure to only leave errors when there is a diff detected.

Actually move screenshot instead of copying

---

src/plugin.js

Thanks for the great plugin. Super concise code!
Looking at [this example code](https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless) from the Cypress documentation, it looks like width and height are swapped. I've fixed this and also added support for firefox and electron runners.

fix: swap width/height, support electron and firefox

---

src/plugin.js

Hello,
Thank you for your great library.
This is just a little fix for electron use.
Electron expects its width and height as integer, not as string.
I tested this on Windows 10 and Ubuntu 21.04.
Linted and Tests pass. 
Best wishes,
Andreas

fix: electron requires numbers as parameters

---

src/command.js
src/plugin.js

I created a bug with reporting in #63. Each time we call `cy.compareScreenshot` a new `TestStatus` object gets added. However, if we are retrying `cy.compareScreenshot` over and over, we only care about the last `TestStatus` (for the same reason we only care about the last screenshot taken).
We just need to clear the previous `TestStatus` the same way we clear the previous comparison/diff screenshot.
`main`
https://user-images.githubusercontent.com/13155517/147292991-d86f5db6-8535-47d4-942f-4ba97ef8fb34.mp4
`fix/retry-reporting`
https://user-images.githubusercontent.com/13155517/147292999-dcf62525-c12a-4bfb-8de3-b334b9845f61.mp4

Fix: Reporting and Retries

---

src/command.js

fix #68 
and
fix #74 
properly as command.js was still reading from the environment variables instead of the cypress.json before using the fallback sizes

fix: use cypress config to force resolution viewport size everywhere

---

README.md
cypress/specs/image-diff-spec.js
src/command.js
src/plugin.js

This is useful when you want to just generate full report with failed snapshots. 
Our project is changing fast and forcing all visual tests to fail makes it hard to maintain visual tests. We would like to use cypress-image-diff to review all visual changes periodically, but we do not want to fail full e2e test suite each time.
Sorry for not contacting to about this feature earlier, but it's a simple change so I just created and we can discuss it in this MR.
This changes api a bit (adds options object instead of threshold) but it is fully backward compatible.

feat: Add compareSnapshot option to allow test failure

---

README.md
src/plugin.js
src/utils.js
src/utils.test.js

It may be useful to preserve the screenshots in their original location rather that moving it under the new screenshot folder structure. This will provide an option for addressing the failure screenshots becoming undefined files under the new folder structure and any other incompatibilities with reporting plugins that might be expecting screenshots in the standard Cypress location.

Add param to preserve original screenshot location

---

docs/Cypress integration.md
docs/Reporting.md

This PR adds documentation that hopefully closes #89. I did preliminary testing and found that this library works out of the box with Cypress 10+ with no issues (only tested on 10.3.1, but I agree with @PippoRaimondi that it should work with 10.0.0 and above.)
Additionally, did some reformatting on the `docs/Cypress Integration.md` file to add `sh` tag to the command line installation instructions.
Definitely open to changing and updating the language used.

docs: add documentation on Cypress 10 setup

---

package-lock.json
package.json

Cypress should be a peerDependency to ensure users don't accidentally download multiple copies of Cypress. Nominally the package supports cypress 10 according to https://github.com/uktrade/cypress-image-diff/issues/89 so it should be added as an option.
Note that Cypress 10 support may not be fully accurate until this issue is addressed:
- https://github.com/uktrade/cypress-image-diff/issues/112
Addresses:
- https://github.com/uktrade/cypress-image-diff/issues/87

chore: move cypress to peerDependencies, allow v10

---

docs/Cypress integration.md

- sync the style of quotation marks;
- add a missing parenthesis.

Fix formatting of Cypress integration doc

---

docs/Cypress integration.md

Hi, thanks for this plugin, seems nice! 🙌
A quick PR to add TypeScript config docs for the project and rework for consistency:
1. Move v10+ to the start in second example
2. Eliminate `cypress/support/commands.js` because this is no longer standard in Cypress v10+

Add TypeScript config docs

---

package-lock.json
package.json
src/cli.js
src/cli.test.js

Because colors has an issue with an endless loop it will not work with newer node versions. https://github.com/Marak/colors.js/issues/345 To avoid this endless loop i updated from colors library to newer @colors/colors library which has fixed this issue.

feat: update to @colors/colors to fix endless loop in cli

---

README.md
src/config.js
src/config.test.js
src/plugin.js

This is an attempt to fix hardcoded test folder, issue #9 #137 
This configuration is optional, shouldn't break current version.
I deliberately pass a third configuration option object to `getCompareSnapshotsPlugin`. I think there are a few benefits:
- scalable: There are more custom configurations that users could pass in later on that I could potentially see now, such as failureThreshold and retryOptions. At the moment, these two options can only be passed in at command level. It would be nice if we could have global configurations at plugin level that act more like defaults or fallbacks, so we don't have to pass them in for every command. (This will be in future pull requests)
- encapsulated: I could actually ask users to define `rootDir` under their e2e folder, then access via cypress …

feat: add rootDir configuration option

---

src/command.js

fixes [https://github.com/uktrade/cypress-image-diff/pull/96#issuecomment-1215300863](url)

fix: Remove unexpected '-' in nested folder screenshot names

---

src/reporter/__snapshots__/reporter.test.js.snap
src/reporter/template.hbs

Error creating report if taking pictures with nested folders.
Example: cypress-visual-screenshots/comparison/folder-1/folder-2/image.png

fix: creating report if taking pictures with nested folders

---

README.md
docs/Reporting.md
package-lock.json
package.json
report-example.json
src/command.js
src/config.js
src/plugin.js
src/reporter/test-status.js
src/utils.js
src/utils.test.js

There are two main reasons I want to implement this feature:
- Decouple our current default HTML report from this plugin's core function and move it into its own repository: There is more room for us to grow there. I've got a few feature ideas in mind that I'll be working on in the near future, such as a cool side-by-side comparison, updating one or more snapshots with a click (#120, #107 ), re-running a particular test suit, and clicking a test suit to view its original spec file in the default IDE. These features would be much easier to develop and maintain with a front-end framework like Vue or React and a node server. Hence, it should deserve its own repository. Plus, it doesn't benefit users who don't need a report but burdens the plugin's size.
- Users can have a custom report of …

Feat: add an option to generate custom html report

---

src/command.js
src/config.default.js
src/config.js

Fixes #172. For users who want to use the default configuration and not return `getCompareSnapshotsPlugin` instance inside the function `setupNodeEvents`

fix: set default user config when cypressImageDiff undefined

---

.github/workflows/issue_watcher.yml

- Mark inactive issues as stale after 30 days
- Close stale issues after 30 days

chore: workflow automation

---

src/command.js

For tests using .ts files, when get screenshots, the file name will be `[name].ts`. This is not consistent with .js files

feat: replace .ts file extension

---

src/config.js
types/plugin.d.ts

This pull request fixes #192
CommonJS doesn't support importing ESM modules with `require` statements, and because our plugin is shipped as CommonJs, we fail to resolve the user config file `cypress-image-diff.config.js` in those projects that are ESM modules.

fix: add an escape hatch for esm config file

---

package.json

fix: add explicit .js extension for project module exporting

---

package.json

Fixes #198. Add support fallback import for command function for Cypress v12.17.3 and older
```
import getCompareSnapshotsPlugin from 'cypress-image-diff-js'
// is an alias for:
// import getCompareSnapshotsPlugin from 'cypress-image-diff-js/command'
```
```diff
For Cypress v12.17.3 and older:
- import getCompareSnapshotsPlugin from 'cypress-image-diff-js/command'
+ import getCompareSnapshotsPlugin from 'cypress-image-diff-js'
```

fix: add support fallback import for command

---

src/plugin.js

Catches error when comparison file isn't loaded. Issue explained in full here: https://github.com/uktrade/cypress-image-diff/issues/209
Could you please review? This issue is currently biting us at our organisation.

fix: Catch comparison file load failure and trigger test failure

---

package.json

Issue #208 
Fixes Error: 
Webpack Compilation Error
Module not found: Error: Package path ./dist/config.default is not exported from package /Users/XXX/work/visual_regression_testing/node_modules/cypress-image-diff-js (see exports field in /Users/XXX/work/visual_regression_testing/node_modules/cypress-image-diff-js/package.json)

#208 fixes module not found

---

src/command.js
src/config.default.js
src/plugin.js
src/utils.js

I'm working on this [pull request](https://github.com/kien-ht/cypress-image-diff-html-report/pull/14) at the moment.
This inline assets feature is actually available in the HTML Report package, but turns out it would be better to have this in the core package, as the output JSON could be already base64-ed.

feat: add INLINE_ASSETS config option

---

src/plugin.js

After merging #216 , I found a problem with diff image generations, that the base64 conversion is incomplete because the diff generations are writable streams.

fix: incomplete diff base64
